experiment:
  name: demo

paths:
  savepath_emissions: data/emissions/
  savepath_met: data/met/
  checkpoint: experiments/demo/checkpoints/demo_model_ep49.pt
  output_loc: experiments/demo/infer/
  min_max_file: data/stats/min_max.mat

data:
  dataset: val     
  ntest: 128
  total_time: 26
  time_input: 10
  time_out: 16
  S1: 140
  S2: 124

features:
  V: 4
  met_variables: ['pm25','t2','rain']
  emission_variables:
    - ['PM25_e','PM25_finn']

  single_variables: []
  mean_names: []

model:
  modes: 12
  width: 20

inference:
  forward_steps: 1
