paths:
  raw_path: data/raw
  savepath_met: data/met
  savepath_emissions: data/emissions

data:
  months: ["APRIL_16_HOURLY"]
  horizon: 26
  stride: 1
  spin_up: 48
  val_frac: 0.2
  seed: 0

features:
  met_variables_raw:
    - pm25
    - t2
    - rainc
    - rainnc

  emission_variables_raw:
    - PM25_e
    - PM25_finn
