experiment:
  exp_name: demo

paths:
  savepath_emissions: data/emissions/
  savepath_met: data/met/
  min_max_file: data/stats/min_max.mat
  save_dir: experiments/demo/logs/log.json
  model_save_path: experiments/demo/checkpoints/demo_model.pt


data:
  ntrain: 514
  ntest: 128
  total_time: 26
  time_input: 10
  time_out: 16
  S1: 140
  S2: 124

features:
  V: 4
  met_variables: ['pm25','t2','rain']
  emission_variables:
    - ['PM25_e','PM25_finn']

  single_variables: []
  mean_names: []

model:
  modes: 12
  width: 20

training:
  batch_size: 4
  epochs: 50
  lr: 0.001
  weight_decay: 1e-4
  scheduler_step: 50
  scheduler_gamma: 0.5
  checkpoint_every: 10
