paths:
  pred_path: experiments/baseline/eval/val.npy
  actual_path: data/met/val_pm25.npy
  save_dir: experiments/baseline/results/

data:
  dataset: val
  ntest: 528
  time_input: 10

cities:
  delhi: [[93,38],[94,38],[93,37],[93,39],[94,39]]
  lucknow: [[85,53],[85,54]]
  mumbai: [[50,21],[51,21],[50,20]]
  bhopal: [[69,39]]
  ahmedabad: [[68,20],[68,19],[67,19]]
  jaipur: [[85,33],[85,32]]
  bengaluru: [[25,40],[24,40]]
  hyderabad: [[43,43],[44,43],[44,44],[43,44],[44,42]]
  dehradun: [[101,42]]
  shimla: [[105,38]]
  guwahati: [[82,98],[82,97]]
  kohima: [[80,107]]
