experiment:
  device: cuda
  name: baseline_infer

paths:
  savepath_emissions: data/emissions/
  savepath_met: data/met/
  min_max_file: data/stats/min_max.mat

  checkpoint: experiments/baseline/checkpoints/fno_baseline_ep300.pt
  output_file: experiments/baseline/eval/val.npy

data:
  dataset: val     
  ntest: 528
  total_time: 26
  time_input: 10
  time_out: 16
  S1: 140
  S2: 124

features:
  V: 16
  met_variables: ['pm25','q2','t2','u10','swdown','pblh','v10','psfc']
  emission_variables:
    - ['PM25_e','PM25_finn']
    - ['NH3_e','NH3_finn']
    - ['SO2_e','SO2_finn']
    - ['NOx_e','NOx_finn']
  single_variables: ['NMVOC_e','NMVOC_finn','bio']
  mean_names: ['NMVOCE','NMVOCfinn','isobio']

model:
  modes: 12
  width: 20

inference:
  forward_steps: 1
