experiment:
  name: baseline

paths:
  input_loc: data/val/
  checkpoint: experiments/baseline/checkpoints/fno_baseline_ep499.pt
  output_loc: experiments/baseline/infer/
  min_max_file: data/stats/feat_min_max.mat

data:
  dataset: val     
  ntest: 528
  total_time: 26
  time_input: 10
  time_out: 16
  S1: 140
  S2: 124

features:
  V: 16
  met_variables: ['pm25','q2','t2','u10','swdown','pblh','v10','psfc','rain']
  emission_variables:
    - 'PM25'
    - 'NH3'
    - 'SO2'
    - 'NOx'
    - 'NMVOC_e'
    - 'NMVOC_finn'
    - 'bio'

model:
  modes: 12
  width: 20


