paths:
  raw_path: data/raw
  train_savepath_met: data/train/met
  train_savepath_emissions: data/train/emissions
  val_savepath_met: data/train/met
  val_savepath_emissions: data/train/emissions

data:
  months: ["APRIL_16",'JULY_16','OCT_16','DEC_16']
  horizon: 26
  stride: 1
  spin_up: 48
  val_frac: 0.2
  seed: 0

features:
  met_variables_raw:
    - pm25
    - q2
    - t2
    - u10
    - v10
    - swdown
    - pblh
    - psfc
    - rain

  emission_variables_raw:
    - PM25
    - NH3
    - SO2
    - NOx
    - NMVOC_e
    - NMVOC_finn
    - bio
