experiment:
  exp_name: fno_baseline

paths:
  savepath: /kaggle/tmp/data/train/
  min_max_file: /kaggle/input/aise-hack-test/data/stats/feat_min_max.mat
  save_dir: /kaggle/working/experiments/baseline/logs/log.json
  model_save_path: /kaggle/working/experiments/baseline/checkpoints/fno_baseline.pt


data:
  ntrain: 2112
  ntest: 528
  total_time: 26
  time_input: 10
  time_out: 16
  S1: 140
  S2: 124

features:
  V: 16
  met_variables: ['cpm25','q2','t2','u10','swdown','pblh','v10','psfc','rain']
  emission_variables:
    - 'PM25'
    - 'NH3'
    - 'SO2'
    - 'NOx'
    - 'NMVOC_e'
    - 'NMVOC_finn'
    - 'bio'

model:
  modes: 12
  width: 20

training:
  batch_size: 4
  epochs: 500
  lr: 0.001
  weight_decay: 1e-4
  scheduler_step: 50
  scheduler_gamma: 0.5
  checkpoint_every: 100
