experiment:
  exp_name: anrf_fno

paths:
  savepath_emissions: data/emissions/
  savepath_met: data/met/
  min_max_file: data/stats/min_max.mat
  save_dir: experiments/baseline/logs/log.json
  model_save_path: experiments/baseline/checkpoints/fno_baseline.pt


data:
  ntrain: 2112
  ntest: 528
  total_time: 26
  time_input: 10
  time_out: 16
  S1: 140
  S2: 124

features:
  V: 16
  met_variables: ['pm25','q2','t2','u10','swdown','pblh','v10','psfc','rain']
  emission_variables:
    - ['PM25_e','PM25_finn']
    - ['NH3_e','NH3_finn']
    - ['SO2_e','SO2_finn']
    - ['NOx_e','NOx_finn']
  single_variables: ['NMVOC_e','NMVOC_finn','bio']
  mean_names: ['NMVOCE','NMVOCfinn','isobio']

model:
  modes: 12
  width: 20

training:
  batch_size: 4
  epochs: 500
  lr: 0.001
  weight_decay: 1e-4
  scheduler_step: 50
  scheduler_gamma: 0.5
  checkpoint_every: 100
